spring.application.name=agentic
spring.docker.compose.enabled=false

# Connection
spring.ai.google.genai.api-key=${GEMINI_API_KEY}

# Model Selection (Standardized in 2.0)
spring.ai.google.genai.chat.options.model=gemini-2.5-flash-lite
spring.ai.google.genai.chat.options.temperature=0.7

# Slack
slack.user.token=${USER_TOKEN_SLACK}
slack.bot.token=${BOT_TOKEN_SLACK}

# Optional: Explicitly enable this specific chat model
spring.ai.model.chat=google-genai

logging.level.org.springframework.ai=DEBUG